######################################################################
# Automatically generated by qmake (2.01a) Tue Aug 16 14:49:44 2011
######################################################################

CONFIG = console
TEMPLATE = app
TARGET = twmnc
DEPENDPATH += .
INCLUDEPATH += .
DESTDIR = ../bin/
LIBS += -lboost_program_options -lboost_system -lpthread
target.path += /usr/local/bin
INSTALLS += target
# Input
SOURCES += main.cpp
